name: ct
channels:
  - defaults
  - conda-forge
  - fastai
dependencies:
  - python=3
  - ipywidgets<8
  - numpy
  - matplotlib
  - scipy
  - voila
  - librosa
  - ipympl
  - fastcore
  - bokeh
  - jupyter_bokeh
  - plotly
  - pandas
