name: ct
channels:
  - defaults
  - conda-forge
dependencies:
  - python
  - ipywidgets
  - voila
  - plotly
  - numpy
  - scipy
  - librosa
  - pandas
  - standard-aifc
  - fastcore
  - anywidget
  - ipympl
