name: ct
channels:
  - defaults
  - conda-forge
  - fastai
dependencies:
  - python=3
  - ipywidgets
  - numpy
  - scipy
  - voila
  - librosa
  - standard-aifc
  - fastcore
  - plotly
  - pandas
  - nodejs
